project:
  type: website

website:
  title: "M. L. DeBusk-Lane, Ph.D."
  search: false
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: CV.qmd
        text: CV
      - href: posts.qmd
        text: Posts
      - href: research.qmd
        text: Research
  page-footer:
    background: dark
    left: Copyright 2026, M.L. DeBusk-Lane, Ph.D.
    right: Built with {{< fa heart title="a heart" >}}, [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/debusklaneml/mldebusklane_q_website/tree/master){target=_blank}, and [Quarto](https://quarto.org/){target=_blank}



format:
  html:
    theme: default
    css:
      - fonts.css
      - terminal.css
      - terminal-quarto-bridge.css
      - styles.css
    include-after-body:
      - theme-toggle.html
    toc: true
    code-copy: true
    code-overflow: wrap


