project:
  type: website

website:
  title: "M. L. DeBusk-Lane, Ph.D."
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: CV.qmd
        text: CV
      - href: posts.qmd
        text: Posts
      - href: research.qmd
        text: Research
  page-footer:
    background: dark
    left: Copyright 2024, M.L. DeBusk-Lane, Ph.D.
    right: This website is built with {{< fa heart title="a heart" >}}, [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/debusklaneml/mldebusklane_q_website/tree/master){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}



format:
  html:
    theme: darkly
    css: styles.css
    toc: true


