project:
  type: website

website:
  title: "M. L. DeBusk-Lane, Ph.D."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

