project:
  type: website

website:
  title: "M. L. DeBusk-Lane, Ph.D."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: CV.qmd
        text: CV
      - href: posts.qmd
        text: Posts
      - href: research.qmd
        text: Research

format:
  html:
    theme: darkly
    css: styles.css
    toc: true


